Simplify assemble.

diff --git a/.sti/bin/assemble b/.sti/bin/assemble
--- a/.sti/bin/assemble
+++ b/.sti/bin/assemble
@@ -2,12 +2,11 @@
 
 env
 
-if [ -z "$JETTY_URL" -o -z "$JETTY_TARBALL" -o -z "$JETTY_DIR" ]; then
-    echo >&2 "ERROR: one of required variables (JETTY_URL, JETTY_TARBALL, JETTY_DIR) have empty value!"
+if [ -z "$JETTY_URL" ]; then
+    echo >&2 "ERROR: JETTY_URL has empty value!"
     exit 1
 fi
 
-wget "$JETTY_URL" -O "$JETTY_TARBALL"
-tar zxvf "$JETTY_TARBALL"
-mv "$JETTY_DIR" $HOME/jetty
+mkdir $HOME/jetty
+wget "$JETTY_URL" -O - | tar zxf - -C $HOME/jetty
 
