Use env variables.

diff --git a/.sti/bin/assemble b/.sti/bin/assemble
--- a/.sti/bin/assemble
+++ b/.sti/bin/assemble
@@ -2,7 +2,12 @@
 
 env
 
-wget 'http://eclipse.org/downloads/download.php?file=/jetty/stable-9/dist/jetty-distribution-9.3.6.v20151106.tar.gz&r=1' -O jetty-distribution-9.3.6.v20151106.tar.gz
-tar zxvf jetty-distribution-9.3.6.v20151106.tar.gz
-mv jetty-distribution-9.3.6.v20151106 $HOME/jetty
+if [ -z "$JETTY_URL" -o -z "$JETTY_TARBALL" -o -z "$JETTY_DIR" ]; then
+    echo >&2 "ERROR: one of required variables (JETTY_URL, JETTY_TARBALL, JETTY_DIR) have empty value!"
+    exit 1
+fi
+
+wget "$JETTY_URL" -O "$JETTY_TARBALL"
+tar zxvf "$JETTY_TARBALL"
+mv "$JETTY_DIR" $HOME/jetty
 
